// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dkdc_ipc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DkdcIpc {

  /// <summary>Holder for reflection information generated from dkdc_ipc.proto</summary>
  public static partial class DkdcIpcReflection {

    #region Descriptor
    /// <summary>File descriptor for dkdc_ipc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DkdcIpcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5ka2RjX2lwYy5wcm90bxIIZGtkY19pcGMiGAoIT3BlblBvcnQSDAoEcG9y",
            "dBgBIAEoCSILCglDbG9zZVBvcnQiHwoLQnV0dG9uQ2xpY2sSEAoIYnV0dG9u",
            "SWQYASABKA0iHQoKUXVlcnlJbnB1dBIPCgdpbnB1dElkGAEgASgNIisKCUlu",
            "cHV0RGF0YRIPCgdpbnB1dElkGAEgASgNEg0KBXZhbHVlGAIgASgBIhkKCUNo",
            "YXJ0RGF0YRIMCgRkYXRhGAEgAygCIiwKB0xvZ0RhdGESFAoMdGltZXN0YW1w",
            "X21zGAEgASgNEgsKA2xvZxgCIAEoCSKnAQoKTm90aWZ5RGF0YRItCgR0eXBl",
            "GAEgASgOMh8uZGtkY19pcGMuTm90aWZ5RGF0YS5Ob3RpZnlUeXBlEg0KBXRp",
            "dGxlGAIgASgJEg8KB21lc3NhZ2UYAyABKAkiSgoKTm90aWZ5VHlwZRIJCgVF",
            "UlJPUhAAEggKBElORk8QARILCgdXQVJOSU5HEAISCwoHU1VDQ0VTUxADEg0K",
            "CUVYQ0VQVElPThAEIssBChhGcm9udGVuZFRvQmFja2VuZE1lc3NhZ2USJgoI",
            "b3BlblBvcnQYASABKAsyEi5ka2RjX2lwYy5PcGVuUG9ydEgAEigKCWNsb3Nl",
            "UG9ydBgCIAEoCzITLmRrZGNfaXBjLkNsb3NlUG9ydEgAEiwKC2J1dHRvbkNs",
            "aWNrGAMgASgLMhUuZGtkY19pcGMuQnV0dG9uQ2xpY2tIABIoCglpbnB1dERh",
            "dGEYBCABKAsyEy5ka2RjX2lwYy5JbnB1dERhdGFIAEIFCgNjbWQinQIKGEJh",
            "Y2tlbmRUb0Zyb250ZW5kTWVzc2FnZRIoCgljbG9zZVBvcnQYFSABKAsyEy5k",
            "a2RjX2lwYy5DbG9zZVBvcnRIABIqCgpub3RpZnlEYXRhGBYgASgLMhQuZGtk",
            "Y19pcGMuTm90aWZ5RGF0YUgAEioKCnF1ZXJ5SW5wdXQYAyABKAsyFC5ka2Rj",
            "X2lwYy5RdWVyeUlucHV0SAASKAoJY2hhcnREYXRhGAQgASgLMhMuZGtkY19p",
            "cGMuQ2hhcnREYXRhSAASJAoHbG9nRGF0YRgFIAEoCzIRLmRrZGNfaXBjLkxv",
            "Z0RhdGFIABIoCglpbnB1dERhdGEYBiABKAsyEy5ka2RjX2lwYy5JbnB1dERh",
            "dGFIAEIFCgNjbWRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DkdcIpc.OpenPort), global::DkdcIpc.OpenPort.Parser, new[]{ "Port" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DkdcIpc.ClosePort), global::DkdcIpc.ClosePort.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DkdcIpc.ButtonClick), global::DkdcIpc.ButtonClick.Parser, new[]{ "ButtonId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DkdcIpc.QueryInput), global::DkdcIpc.QueryInput.Parser, new[]{ "InputId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DkdcIpc.InputData), global::DkdcIpc.InputData.Parser, new[]{ "InputId", "Value" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DkdcIpc.ChartData), global::DkdcIpc.ChartData.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DkdcIpc.LogData), global::DkdcIpc.LogData.Parser, new[]{ "TimestampMs", "Log" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DkdcIpc.NotifyData), global::DkdcIpc.NotifyData.Parser, new[]{ "Type", "Title", "Message" }, null, new[]{ typeof(global::DkdcIpc.NotifyData.Types.NotifyType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DkdcIpc.FrontendToBackendMessage), global::DkdcIpc.FrontendToBackendMessage.Parser, new[]{ "OpenPort", "ClosePort", "ButtonClick", "InputData" }, new[]{ "Cmd" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DkdcIpc.BackendToFrontendMessage), global::DkdcIpc.BackendToFrontendMessage.Parser, new[]{ "ClosePort", "NotifyData", "QueryInput", "ChartData", "LogData", "InputData" }, new[]{ "Cmd" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OpenPort : pb::IMessage<OpenPort>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OpenPort> _parser = new pb::MessageParser<OpenPort>(() => new OpenPort());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OpenPort> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DkdcIpc.DkdcIpcReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenPort() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenPort(OpenPort other) : this() {
      port_ = other.port_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenPort Clone() {
      return new OpenPort(this);
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 1;
    private string port_ = "";
    /// <summary>
    /// Port to open
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Port {
      get { return port_; }
      set {
        port_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OpenPort);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OpenPort other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Port != other.Port) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Port.Length != 0) hash ^= Port.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Port.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Port);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Port.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Port);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Port.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Port);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OpenPort other) {
      if (other == null) {
        return;
      }
      if (other.Port.Length != 0) {
        Port = other.Port;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Port = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Port = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClosePort : pb::IMessage<ClosePort>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClosePort> _parser = new pb::MessageParser<ClosePort>(() => new ClosePort());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClosePort> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DkdcIpc.DkdcIpcReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClosePort() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClosePort(ClosePort other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClosePort Clone() {
      return new ClosePort(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClosePort);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClosePort other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClosePort other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ButtonClick : pb::IMessage<ButtonClick>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ButtonClick> _parser = new pb::MessageParser<ButtonClick>(() => new ButtonClick());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ButtonClick> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DkdcIpc.DkdcIpcReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ButtonClick() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ButtonClick(ButtonClick other) : this() {
      buttonId_ = other.buttonId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ButtonClick Clone() {
      return new ButtonClick(this);
    }

    /// <summary>Field number for the "buttonId" field.</summary>
    public const int ButtonIdFieldNumber = 1;
    private uint buttonId_;
    /// <summary>
    /// ID of the button that was clicked
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ButtonId {
      get { return buttonId_; }
      set {
        buttonId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ButtonClick);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ButtonClick other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ButtonId != other.ButtonId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ButtonId != 0) hash ^= ButtonId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ButtonId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ButtonId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ButtonId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ButtonId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ButtonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ButtonId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ButtonClick other) {
      if (other == null) {
        return;
      }
      if (other.ButtonId != 0) {
        ButtonId = other.ButtonId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ButtonId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ButtonId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class QueryInput : pb::IMessage<QueryInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryInput> _parser = new pb::MessageParser<QueryInput>(() => new QueryInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DkdcIpc.DkdcIpcReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryInput(QueryInput other) : this() {
      inputId_ = other.inputId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryInput Clone() {
      return new QueryInput(this);
    }

    /// <summary>Field number for the "inputId" field.</summary>
    public const int InputIdFieldNumber = 1;
    private uint inputId_;
    /// <summary>
    /// ID of the input to query
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint InputId {
      get { return inputId_; }
      set {
        inputId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InputId != other.InputId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (InputId != 0) hash ^= InputId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InputId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(InputId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InputId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(InputId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (InputId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InputId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryInput other) {
      if (other == null) {
        return;
      }
      if (other.InputId != 0) {
        InputId = other.InputId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            InputId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            InputId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class InputData : pb::IMessage<InputData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InputData> _parser = new pb::MessageParser<InputData>(() => new InputData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InputData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DkdcIpc.DkdcIpcReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InputData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InputData(InputData other) : this() {
      inputId_ = other.inputId_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InputData Clone() {
      return new InputData(this);
    }

    /// <summary>Field number for the "inputId" field.</summary>
    public const int InputIdFieldNumber = 1;
    private uint inputId_;
    /// <summary>
    /// ID of the input
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint InputId {
      get { return inputId_; }
      set {
        inputId_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private double value_;
    /// <summary>
    /// Value of the input (true/false)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InputData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InputData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InputId != other.InputId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Value, other.Value)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (InputId != 0) hash ^= InputId.GetHashCode();
      if (Value != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Value);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InputId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(InputId);
      }
      if (Value != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InputId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(InputId);
      }
      if (Value != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (InputId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InputId);
      }
      if (Value != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InputData other) {
      if (other == null) {
        return;
      }
      if (other.InputId != 0) {
        InputId = other.InputId;
      }
      if (other.Value != 0D) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            InputId = input.ReadUInt32();
            break;
          }
          case 17: {
            Value = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            InputId = input.ReadUInt32();
            break;
          }
          case 17: {
            Value = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChartData : pb::IMessage<ChartData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChartData> _parser = new pb::MessageParser<ChartData>(() => new ChartData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChartData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DkdcIpc.DkdcIpcReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChartData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChartData(ChartData other) : this() {
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChartData Clone() {
      return new ChartData(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_data_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> data_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// Chart data to be posted
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChartData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChartData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!data_.Equals(other.data_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= data_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      data_.WriteTo(output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      data_.WriteTo(ref output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += data_.CalculateSize(_repeated_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChartData other) {
      if (other == null) {
        return;
      }
      data_.Add(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 13: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 13: {
            data_.AddEntriesFrom(ref input, _repeated_data_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LogData : pb::IMessage<LogData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogData> _parser = new pb::MessageParser<LogData>(() => new LogData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DkdcIpc.DkdcIpcReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogData(LogData other) : this() {
      timestampMs_ = other.timestampMs_;
      log_ = other.log_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogData Clone() {
      return new LogData(this);
    }

    /// <summary>Field number for the "timestamp_ms" field.</summary>
    public const int TimestampMsFieldNumber = 1;
    private uint timestampMs_;
    /// <summary>
    /// Timestamp in milliseconds
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimestampMs {
      get { return timestampMs_; }
      set {
        timestampMs_ = value;
      }
    }

    /// <summary>Field number for the "log" field.</summary>
    public const int LogFieldNumber = 2;
    private string log_ = "";
    /// <summary>
    /// Log data to be sent
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Log {
      get { return log_; }
      set {
        log_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TimestampMs != other.TimestampMs) return false;
      if (Log != other.Log) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TimestampMs != 0) hash ^= TimestampMs.GetHashCode();
      if (Log.Length != 0) hash ^= Log.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TimestampMs != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(TimestampMs);
      }
      if (Log.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Log);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TimestampMs != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(TimestampMs);
      }
      if (Log.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Log);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TimestampMs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimestampMs);
      }
      if (Log.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Log);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogData other) {
      if (other == null) {
        return;
      }
      if (other.TimestampMs != 0) {
        TimestampMs = other.TimestampMs;
      }
      if (other.Log.Length != 0) {
        Log = other.Log;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TimestampMs = input.ReadUInt32();
            break;
          }
          case 18: {
            Log = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TimestampMs = input.ReadUInt32();
            break;
          }
          case 18: {
            Log = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NotifyData : pb::IMessage<NotifyData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NotifyData> _parser = new pb::MessageParser<NotifyData>(() => new NotifyData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NotifyData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DkdcIpc.DkdcIpcReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyData(NotifyData other) : this() {
      type_ = other.type_;
      title_ = other.title_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyData Clone() {
      return new NotifyData(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::DkdcIpc.NotifyData.Types.NotifyType type_ = global::DkdcIpc.NotifyData.Types.NotifyType.Error;
    /// <summary>
    /// Type of notification
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.NotifyData.Types.NotifyType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 2;
    private string title_ = "";
    /// <summary>
    /// Title of the error message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    /// <summary>
    /// Error message to be sent
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NotifyData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NotifyData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Title != other.Title) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::DkdcIpc.NotifyData.Types.NotifyType.Error) hash ^= Type.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::DkdcIpc.NotifyData.Types.NotifyType.Error) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::DkdcIpc.NotifyData.Types.NotifyType.Error) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::DkdcIpc.NotifyData.Types.NotifyType.Error) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NotifyData other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::DkdcIpc.NotifyData.Types.NotifyType.Error) {
        Type = other.Type;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::DkdcIpc.NotifyData.Types.NotifyType) input.ReadEnum();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::DkdcIpc.NotifyData.Types.NotifyType) input.ReadEnum();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the NotifyData message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum NotifyType {
        /// <summary>
        /// Error notification
        /// </summary>
        [pbr::OriginalName("ERROR")] Error = 0,
        /// <summary>
        /// Informational notification
        /// </summary>
        [pbr::OriginalName("INFO")] Info = 1,
        /// <summary>
        /// Warning notification
        /// </summary>
        [pbr::OriginalName("WARNING")] Warning = 2,
        /// <summary>
        /// Success notification
        /// </summary>
        [pbr::OriginalName("SUCCESS")] Success = 3,
        /// <summary>
        /// Exception notification
        /// </summary>
        [pbr::OriginalName("EXCEPTION")] Exception = 4,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FrontendToBackendMessage : pb::IMessage<FrontendToBackendMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrontendToBackendMessage> _parser = new pb::MessageParser<FrontendToBackendMessage>(() => new FrontendToBackendMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrontendToBackendMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DkdcIpc.DkdcIpcReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrontendToBackendMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrontendToBackendMessage(FrontendToBackendMessage other) : this() {
      switch (other.CmdCase) {
        case CmdOneofCase.OpenPort:
          OpenPort = other.OpenPort.Clone();
          break;
        case CmdOneofCase.ClosePort:
          ClosePort = other.ClosePort.Clone();
          break;
        case CmdOneofCase.ButtonClick:
          ButtonClick = other.ButtonClick.Clone();
          break;
        case CmdOneofCase.InputData:
          InputData = other.InputData.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrontendToBackendMessage Clone() {
      return new FrontendToBackendMessage(this);
    }

    /// <summary>Field number for the "openPort" field.</summary>
    public const int OpenPortFieldNumber = 1;
    /// <summary>
    /// Send to backend to open Serial port
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.OpenPort OpenPort {
      get { return cmdCase_ == CmdOneofCase.OpenPort ? (global::DkdcIpc.OpenPort) cmd_ : null; }
      set {
        cmd_ = value;
        cmdCase_ = value == null ? CmdOneofCase.None : CmdOneofCase.OpenPort;
      }
    }

    /// <summary>Field number for the "closePort" field.</summary>
    public const int ClosePortFieldNumber = 2;
    /// <summary>
    /// Send to backend to close Serial port
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.ClosePort ClosePort {
      get { return cmdCase_ == CmdOneofCase.ClosePort ? (global::DkdcIpc.ClosePort) cmd_ : null; }
      set {
        cmd_ = value;
        cmdCase_ = value == null ? CmdOneofCase.None : CmdOneofCase.ClosePort;
      }
    }

    /// <summary>Field number for the "buttonClick" field.</summary>
    public const int ButtonClickFieldNumber = 3;
    /// <summary>
    /// Send to backend when a button is clicked
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.ButtonClick ButtonClick {
      get { return cmdCase_ == CmdOneofCase.ButtonClick ? (global::DkdcIpc.ButtonClick) cmd_ : null; }
      set {
        cmd_ = value;
        cmdCase_ = value == null ? CmdOneofCase.None : CmdOneofCase.ButtonClick;
      }
    }

    /// <summary>Field number for the "inputData" field.</summary>
    public const int InputDataFieldNumber = 4;
    /// <summary>
    /// Reponse for QueryInput Message 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.InputData InputData {
      get { return cmdCase_ == CmdOneofCase.InputData ? (global::DkdcIpc.InputData) cmd_ : null; }
      set {
        cmd_ = value;
        cmdCase_ = value == null ? CmdOneofCase.None : CmdOneofCase.InputData;
      }
    }

    private object cmd_;
    /// <summary>Enum of possible cases for the "cmd" oneof.</summary>
    public enum CmdOneofCase {
      None = 0,
      OpenPort = 1,
      ClosePort = 2,
      ButtonClick = 3,
      InputData = 4,
    }
    private CmdOneofCase cmdCase_ = CmdOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdOneofCase CmdCase {
      get { return cmdCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCmd() {
      cmdCase_ = CmdOneofCase.None;
      cmd_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrontendToBackendMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrontendToBackendMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OpenPort, other.OpenPort)) return false;
      if (!object.Equals(ClosePort, other.ClosePort)) return false;
      if (!object.Equals(ButtonClick, other.ButtonClick)) return false;
      if (!object.Equals(InputData, other.InputData)) return false;
      if (CmdCase != other.CmdCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (cmdCase_ == CmdOneofCase.OpenPort) hash ^= OpenPort.GetHashCode();
      if (cmdCase_ == CmdOneofCase.ClosePort) hash ^= ClosePort.GetHashCode();
      if (cmdCase_ == CmdOneofCase.ButtonClick) hash ^= ButtonClick.GetHashCode();
      if (cmdCase_ == CmdOneofCase.InputData) hash ^= InputData.GetHashCode();
      hash ^= (int) cmdCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (cmdCase_ == CmdOneofCase.OpenPort) {
        output.WriteRawTag(10);
        output.WriteMessage(OpenPort);
      }
      if (cmdCase_ == CmdOneofCase.ClosePort) {
        output.WriteRawTag(18);
        output.WriteMessage(ClosePort);
      }
      if (cmdCase_ == CmdOneofCase.ButtonClick) {
        output.WriteRawTag(26);
        output.WriteMessage(ButtonClick);
      }
      if (cmdCase_ == CmdOneofCase.InputData) {
        output.WriteRawTag(34);
        output.WriteMessage(InputData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (cmdCase_ == CmdOneofCase.OpenPort) {
        output.WriteRawTag(10);
        output.WriteMessage(OpenPort);
      }
      if (cmdCase_ == CmdOneofCase.ClosePort) {
        output.WriteRawTag(18);
        output.WriteMessage(ClosePort);
      }
      if (cmdCase_ == CmdOneofCase.ButtonClick) {
        output.WriteRawTag(26);
        output.WriteMessage(ButtonClick);
      }
      if (cmdCase_ == CmdOneofCase.InputData) {
        output.WriteRawTag(34);
        output.WriteMessage(InputData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (cmdCase_ == CmdOneofCase.OpenPort) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OpenPort);
      }
      if (cmdCase_ == CmdOneofCase.ClosePort) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClosePort);
      }
      if (cmdCase_ == CmdOneofCase.ButtonClick) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ButtonClick);
      }
      if (cmdCase_ == CmdOneofCase.InputData) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InputData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrontendToBackendMessage other) {
      if (other == null) {
        return;
      }
      switch (other.CmdCase) {
        case CmdOneofCase.OpenPort:
          if (OpenPort == null) {
            OpenPort = new global::DkdcIpc.OpenPort();
          }
          OpenPort.MergeFrom(other.OpenPort);
          break;
        case CmdOneofCase.ClosePort:
          if (ClosePort == null) {
            ClosePort = new global::DkdcIpc.ClosePort();
          }
          ClosePort.MergeFrom(other.ClosePort);
          break;
        case CmdOneofCase.ButtonClick:
          if (ButtonClick == null) {
            ButtonClick = new global::DkdcIpc.ButtonClick();
          }
          ButtonClick.MergeFrom(other.ButtonClick);
          break;
        case CmdOneofCase.InputData:
          if (InputData == null) {
            InputData = new global::DkdcIpc.InputData();
          }
          InputData.MergeFrom(other.InputData);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::DkdcIpc.OpenPort subBuilder = new global::DkdcIpc.OpenPort();
            if (cmdCase_ == CmdOneofCase.OpenPort) {
              subBuilder.MergeFrom(OpenPort);
            }
            input.ReadMessage(subBuilder);
            OpenPort = subBuilder;
            break;
          }
          case 18: {
            global::DkdcIpc.ClosePort subBuilder = new global::DkdcIpc.ClosePort();
            if (cmdCase_ == CmdOneofCase.ClosePort) {
              subBuilder.MergeFrom(ClosePort);
            }
            input.ReadMessage(subBuilder);
            ClosePort = subBuilder;
            break;
          }
          case 26: {
            global::DkdcIpc.ButtonClick subBuilder = new global::DkdcIpc.ButtonClick();
            if (cmdCase_ == CmdOneofCase.ButtonClick) {
              subBuilder.MergeFrom(ButtonClick);
            }
            input.ReadMessage(subBuilder);
            ButtonClick = subBuilder;
            break;
          }
          case 34: {
            global::DkdcIpc.InputData subBuilder = new global::DkdcIpc.InputData();
            if (cmdCase_ == CmdOneofCase.InputData) {
              subBuilder.MergeFrom(InputData);
            }
            input.ReadMessage(subBuilder);
            InputData = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::DkdcIpc.OpenPort subBuilder = new global::DkdcIpc.OpenPort();
            if (cmdCase_ == CmdOneofCase.OpenPort) {
              subBuilder.MergeFrom(OpenPort);
            }
            input.ReadMessage(subBuilder);
            OpenPort = subBuilder;
            break;
          }
          case 18: {
            global::DkdcIpc.ClosePort subBuilder = new global::DkdcIpc.ClosePort();
            if (cmdCase_ == CmdOneofCase.ClosePort) {
              subBuilder.MergeFrom(ClosePort);
            }
            input.ReadMessage(subBuilder);
            ClosePort = subBuilder;
            break;
          }
          case 26: {
            global::DkdcIpc.ButtonClick subBuilder = new global::DkdcIpc.ButtonClick();
            if (cmdCase_ == CmdOneofCase.ButtonClick) {
              subBuilder.MergeFrom(ButtonClick);
            }
            input.ReadMessage(subBuilder);
            ButtonClick = subBuilder;
            break;
          }
          case 34: {
            global::DkdcIpc.InputData subBuilder = new global::DkdcIpc.InputData();
            if (cmdCase_ == CmdOneofCase.InputData) {
              subBuilder.MergeFrom(InputData);
            }
            input.ReadMessage(subBuilder);
            InputData = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BackendToFrontendMessage : pb::IMessage<BackendToFrontendMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BackendToFrontendMessage> _parser = new pb::MessageParser<BackendToFrontendMessage>(() => new BackendToFrontendMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BackendToFrontendMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DkdcIpc.DkdcIpcReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BackendToFrontendMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BackendToFrontendMessage(BackendToFrontendMessage other) : this() {
      switch (other.CmdCase) {
        case CmdOneofCase.ClosePort:
          ClosePort = other.ClosePort.Clone();
          break;
        case CmdOneofCase.NotifyData:
          NotifyData = other.NotifyData.Clone();
          break;
        case CmdOneofCase.QueryInput:
          QueryInput = other.QueryInput.Clone();
          break;
        case CmdOneofCase.ChartData:
          ChartData = other.ChartData.Clone();
          break;
        case CmdOneofCase.LogData:
          LogData = other.LogData.Clone();
          break;
        case CmdOneofCase.InputData:
          InputData = other.InputData.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BackendToFrontendMessage Clone() {
      return new BackendToFrontendMessage(this);
    }

    /// <summary>Field number for the "closePort" field.</summary>
    public const int ClosePortFieldNumber = 21;
    /// <summary>
    /// Send to frontend if Serial port is closed
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.ClosePort ClosePort {
      get { return cmdCase_ == CmdOneofCase.ClosePort ? (global::DkdcIpc.ClosePort) cmd_ : null; }
      set {
        cmd_ = value;
        cmdCase_ = value == null ? CmdOneofCase.None : CmdOneofCase.ClosePort;
      }
    }

    /// <summary>Field number for the "notifyData" field.</summary>
    public const int NotifyDataFieldNumber = 22;
    /// <summary>
    /// Notification data to be sent
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.NotifyData NotifyData {
      get { return cmdCase_ == CmdOneofCase.NotifyData ? (global::DkdcIpc.NotifyData) cmd_ : null; }
      set {
        cmd_ = value;
        cmdCase_ = value == null ? CmdOneofCase.None : CmdOneofCase.NotifyData;
      }
    }

    /// <summary>Field number for the "queryInput" field.</summary>
    public const int QueryInputFieldNumber = 3;
    /// <summary>
    /// Request to query input data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.QueryInput QueryInput {
      get { return cmdCase_ == CmdOneofCase.QueryInput ? (global::DkdcIpc.QueryInput) cmd_ : null; }
      set {
        cmd_ = value;
        cmdCase_ = value == null ? CmdOneofCase.None : CmdOneofCase.QueryInput;
      }
    }

    /// <summary>Field number for the "chartData" field.</summary>
    public const int ChartDataFieldNumber = 4;
    /// <summary>
    /// Chart data to be posted
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.ChartData ChartData {
      get { return cmdCase_ == CmdOneofCase.ChartData ? (global::DkdcIpc.ChartData) cmd_ : null; }
      set {
        cmd_ = value;
        cmdCase_ = value == null ? CmdOneofCase.None : CmdOneofCase.ChartData;
      }
    }

    /// <summary>Field number for the "logData" field.</summary>
    public const int LogDataFieldNumber = 5;
    /// <summary>
    /// Log data to be sent
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.LogData LogData {
      get { return cmdCase_ == CmdOneofCase.LogData ? (global::DkdcIpc.LogData) cmd_ : null; }
      set {
        cmd_ = value;
        cmdCase_ = value == null ? CmdOneofCase.None : CmdOneofCase.LogData;
      }
    }

    /// <summary>Field number for the "inputData" field.</summary>
    public const int InputDataFieldNumber = 6;
    /// <summary>
    /// Message to Update input field
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DkdcIpc.InputData InputData {
      get { return cmdCase_ == CmdOneofCase.InputData ? (global::DkdcIpc.InputData) cmd_ : null; }
      set {
        cmd_ = value;
        cmdCase_ = value == null ? CmdOneofCase.None : CmdOneofCase.InputData;
      }
    }

    private object cmd_;
    /// <summary>Enum of possible cases for the "cmd" oneof.</summary>
    public enum CmdOneofCase {
      None = 0,
      ClosePort = 21,
      NotifyData = 22,
      QueryInput = 3,
      ChartData = 4,
      LogData = 5,
      InputData = 6,
    }
    private CmdOneofCase cmdCase_ = CmdOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CmdOneofCase CmdCase {
      get { return cmdCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCmd() {
      cmdCase_ = CmdOneofCase.None;
      cmd_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BackendToFrontendMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BackendToFrontendMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ClosePort, other.ClosePort)) return false;
      if (!object.Equals(NotifyData, other.NotifyData)) return false;
      if (!object.Equals(QueryInput, other.QueryInput)) return false;
      if (!object.Equals(ChartData, other.ChartData)) return false;
      if (!object.Equals(LogData, other.LogData)) return false;
      if (!object.Equals(InputData, other.InputData)) return false;
      if (CmdCase != other.CmdCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (cmdCase_ == CmdOneofCase.ClosePort) hash ^= ClosePort.GetHashCode();
      if (cmdCase_ == CmdOneofCase.NotifyData) hash ^= NotifyData.GetHashCode();
      if (cmdCase_ == CmdOneofCase.QueryInput) hash ^= QueryInput.GetHashCode();
      if (cmdCase_ == CmdOneofCase.ChartData) hash ^= ChartData.GetHashCode();
      if (cmdCase_ == CmdOneofCase.LogData) hash ^= LogData.GetHashCode();
      if (cmdCase_ == CmdOneofCase.InputData) hash ^= InputData.GetHashCode();
      hash ^= (int) cmdCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (cmdCase_ == CmdOneofCase.QueryInput) {
        output.WriteRawTag(26);
        output.WriteMessage(QueryInput);
      }
      if (cmdCase_ == CmdOneofCase.ChartData) {
        output.WriteRawTag(34);
        output.WriteMessage(ChartData);
      }
      if (cmdCase_ == CmdOneofCase.LogData) {
        output.WriteRawTag(42);
        output.WriteMessage(LogData);
      }
      if (cmdCase_ == CmdOneofCase.InputData) {
        output.WriteRawTag(50);
        output.WriteMessage(InputData);
      }
      if (cmdCase_ == CmdOneofCase.ClosePort) {
        output.WriteRawTag(170, 1);
        output.WriteMessage(ClosePort);
      }
      if (cmdCase_ == CmdOneofCase.NotifyData) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(NotifyData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (cmdCase_ == CmdOneofCase.QueryInput) {
        output.WriteRawTag(26);
        output.WriteMessage(QueryInput);
      }
      if (cmdCase_ == CmdOneofCase.ChartData) {
        output.WriteRawTag(34);
        output.WriteMessage(ChartData);
      }
      if (cmdCase_ == CmdOneofCase.LogData) {
        output.WriteRawTag(42);
        output.WriteMessage(LogData);
      }
      if (cmdCase_ == CmdOneofCase.InputData) {
        output.WriteRawTag(50);
        output.WriteMessage(InputData);
      }
      if (cmdCase_ == CmdOneofCase.ClosePort) {
        output.WriteRawTag(170, 1);
        output.WriteMessage(ClosePort);
      }
      if (cmdCase_ == CmdOneofCase.NotifyData) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(NotifyData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (cmdCase_ == CmdOneofCase.ClosePort) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ClosePort);
      }
      if (cmdCase_ == CmdOneofCase.NotifyData) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(NotifyData);
      }
      if (cmdCase_ == CmdOneofCase.QueryInput) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(QueryInput);
      }
      if (cmdCase_ == CmdOneofCase.ChartData) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChartData);
      }
      if (cmdCase_ == CmdOneofCase.LogData) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LogData);
      }
      if (cmdCase_ == CmdOneofCase.InputData) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InputData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BackendToFrontendMessage other) {
      if (other == null) {
        return;
      }
      switch (other.CmdCase) {
        case CmdOneofCase.ClosePort:
          if (ClosePort == null) {
            ClosePort = new global::DkdcIpc.ClosePort();
          }
          ClosePort.MergeFrom(other.ClosePort);
          break;
        case CmdOneofCase.NotifyData:
          if (NotifyData == null) {
            NotifyData = new global::DkdcIpc.NotifyData();
          }
          NotifyData.MergeFrom(other.NotifyData);
          break;
        case CmdOneofCase.QueryInput:
          if (QueryInput == null) {
            QueryInput = new global::DkdcIpc.QueryInput();
          }
          QueryInput.MergeFrom(other.QueryInput);
          break;
        case CmdOneofCase.ChartData:
          if (ChartData == null) {
            ChartData = new global::DkdcIpc.ChartData();
          }
          ChartData.MergeFrom(other.ChartData);
          break;
        case CmdOneofCase.LogData:
          if (LogData == null) {
            LogData = new global::DkdcIpc.LogData();
          }
          LogData.MergeFrom(other.LogData);
          break;
        case CmdOneofCase.InputData:
          if (InputData == null) {
            InputData = new global::DkdcIpc.InputData();
          }
          InputData.MergeFrom(other.InputData);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            global::DkdcIpc.QueryInput subBuilder = new global::DkdcIpc.QueryInput();
            if (cmdCase_ == CmdOneofCase.QueryInput) {
              subBuilder.MergeFrom(QueryInput);
            }
            input.ReadMessage(subBuilder);
            QueryInput = subBuilder;
            break;
          }
          case 34: {
            global::DkdcIpc.ChartData subBuilder = new global::DkdcIpc.ChartData();
            if (cmdCase_ == CmdOneofCase.ChartData) {
              subBuilder.MergeFrom(ChartData);
            }
            input.ReadMessage(subBuilder);
            ChartData = subBuilder;
            break;
          }
          case 42: {
            global::DkdcIpc.LogData subBuilder = new global::DkdcIpc.LogData();
            if (cmdCase_ == CmdOneofCase.LogData) {
              subBuilder.MergeFrom(LogData);
            }
            input.ReadMessage(subBuilder);
            LogData = subBuilder;
            break;
          }
          case 50: {
            global::DkdcIpc.InputData subBuilder = new global::DkdcIpc.InputData();
            if (cmdCase_ == CmdOneofCase.InputData) {
              subBuilder.MergeFrom(InputData);
            }
            input.ReadMessage(subBuilder);
            InputData = subBuilder;
            break;
          }
          case 170: {
            global::DkdcIpc.ClosePort subBuilder = new global::DkdcIpc.ClosePort();
            if (cmdCase_ == CmdOneofCase.ClosePort) {
              subBuilder.MergeFrom(ClosePort);
            }
            input.ReadMessage(subBuilder);
            ClosePort = subBuilder;
            break;
          }
          case 178: {
            global::DkdcIpc.NotifyData subBuilder = new global::DkdcIpc.NotifyData();
            if (cmdCase_ == CmdOneofCase.NotifyData) {
              subBuilder.MergeFrom(NotifyData);
            }
            input.ReadMessage(subBuilder);
            NotifyData = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 26: {
            global::DkdcIpc.QueryInput subBuilder = new global::DkdcIpc.QueryInput();
            if (cmdCase_ == CmdOneofCase.QueryInput) {
              subBuilder.MergeFrom(QueryInput);
            }
            input.ReadMessage(subBuilder);
            QueryInput = subBuilder;
            break;
          }
          case 34: {
            global::DkdcIpc.ChartData subBuilder = new global::DkdcIpc.ChartData();
            if (cmdCase_ == CmdOneofCase.ChartData) {
              subBuilder.MergeFrom(ChartData);
            }
            input.ReadMessage(subBuilder);
            ChartData = subBuilder;
            break;
          }
          case 42: {
            global::DkdcIpc.LogData subBuilder = new global::DkdcIpc.LogData();
            if (cmdCase_ == CmdOneofCase.LogData) {
              subBuilder.MergeFrom(LogData);
            }
            input.ReadMessage(subBuilder);
            LogData = subBuilder;
            break;
          }
          case 50: {
            global::DkdcIpc.InputData subBuilder = new global::DkdcIpc.InputData();
            if (cmdCase_ == CmdOneofCase.InputData) {
              subBuilder.MergeFrom(InputData);
            }
            input.ReadMessage(subBuilder);
            InputData = subBuilder;
            break;
          }
          case 170: {
            global::DkdcIpc.ClosePort subBuilder = new global::DkdcIpc.ClosePort();
            if (cmdCase_ == CmdOneofCase.ClosePort) {
              subBuilder.MergeFrom(ClosePort);
            }
            input.ReadMessage(subBuilder);
            ClosePort = subBuilder;
            break;
          }
          case 178: {
            global::DkdcIpc.NotifyData subBuilder = new global::DkdcIpc.NotifyData();
            if (cmdCase_ == CmdOneofCase.NotifyData) {
              subBuilder.MergeFrom(NotifyData);
            }
            input.ReadMessage(subBuilder);
            NotifyData = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
